development:
  adapter: postgresql
  encoding: utf8
  database: birds_development
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: birds_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: bird
  pool: 5

